// Mocks generated by Mockito 5.0.7 from annotations
// in pip_mvp_flutter/test/cubit_contacts_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pip_mvp_flutter/feature/homepage/model/contact.dart' as _i4;
import 'package:pip_mvp_flutter/feature/homepage/repository/contact_repository_interface.dart'
    as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [IContactRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIContactRepository extends _i1.Mock
    implements _i2.IContactRepository {
  MockIContactRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ContactV1>> getContact() =>
      (super.noSuchMethod(Invocation.method(#getContact, []),
              returnValue: Future<List<_i4.ContactV1>>.value(<_i4.ContactV1>[]))
          as _i3.Future<List<_i4.ContactV1>>);
}
