name: pip_mvp_flutter
description: A sample project by PipSolution.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.22.0
  http: ^0.13.1
  shared_preferences: ^2.0.4
  surf_lint_rules: any

dev_dependencies:
  bloc_test: ^8.0.0
  build_runner: ^1.12.2
  mockito: ^5.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

